baseurl = "https://vcmi.eu/"
languageCode = "en-us"
title = "VCMI Project"
theme = "chronicles"
preserveTaxonomyNames = true
paginate = 3
disqusShortname = ""
googleAnalytics = ""

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "VCMI is an open-source engine for Heroes of Might and Magic III"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "VCMI engine"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/news/"

# Optional Params
    categoriesByCount    = true
    includeReadingTime   = false
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]

# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "VCMI engine"
    paragraph = "Open-source engine for <nobr>Heroes of Might and Magic III</nobr>"
    about     = "VCMI is work-in-progress attempt to recreate engine for Heroes III, giving it new and extended possibilities. To use VCMI you need to own original data files."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/logo.png"
    width     = "200"
    alt       = "VCMI project"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text
[[menu.main]]
    name = "About"
    url = "/about"
    weight = 1

[[menu.main]]
    name = "Forums"
    url = "https://forum.vcmi.eu/"
    identifier = "fa fa-comments"
    weight = 20

[[menu.main]]
    name = "Wiki"
    url = "https://wiki.vcmi.eu/"
    identifier = "fa fa-book"
    weight = 30

[[menu.main]]
    name = "Bugs"
    url = "https://bugs.vcmi.eu/"
    identifier = "fa fa-bug"
    weight = 40

[[menu.main]]
    name = "Slack"
    url = "https://slack.vcmi.eu/"
    identifier = "fa fa-slack"
    weight = 50

[[menu.main]]
    name = "GitHub"
    url = "https://github.com/vcmi/vcmi"
    identifier = "fa fa-github"
    weight = 60

# Platform download list
[[menu.platforms]]
    name = "Windows"
    url = "https://wiki.vcmi.eu/Installation_on_Windows"
    identifier = "fa fa-4x fa-windows"
    weight = 10

[[menu.platforms]]
    name = "macOS"
    url = "https://wiki.vcmi.eu/Installation_on_macOS"
    identifier = "fa fa-4x fa-apple"
    weight = 20

[[menu.platforms]]
    name = "Linux"
    url = "https://wiki.vcmi.eu/Installation_on_Linux"
    identifier = "fa fa-4x fa-linux"
    weight = 30

[[menu.platforms]]
    name = "Android"
    url = "https://wiki.vcmi.eu/Installation_on_Android"
    identifier = "fa fa-4x fa-android"
    weight = 40

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar

[[menu.social]]
    name = "Facebook"
    url = "https://facebook.com/VCMIOfficial"
    identifier = "fa fa-2x fa-facebook"
    weight = 10

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/VCMIOfficial"
    identifier = "fa fa-2x fa-twitter"
    weight = 20

[[menu.social]]
    name = "Google+"
    url = "https://google.com/+VCMIOfficial"
    weight = 30
    identifier = "fa fa-2x fa-google-plus"

[[menu.social]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCUG0_L0mQo-Mq8ajPpHRGgw"
    weight = 40
    identifier = "fa fa-2x fa-youtube"

[[menu.social]]
    name = "Reddit"
    url = "https://reddit.com/r/vcmi/"
    weight = 50
    identifier = "fa fa-2x fa-reddit"

[[menu.social]]
    name = "Steam"
    url = "https://steamcommunity.com/groups/VCMI"
    weight = 60
    identifier = "fa fa-2x fa-steam-square"

[[menu.social]]
    name = "VKontakte"
    url = "https://vk.com/VCMIOfficial"
    weight = 70
    identifier = "fa fa-2x fa-vk"

[[menu.social]]
    name = "Mod DB"
    url = "http://www.moddb.com/engines/vcmi"
    weight = 80
    identifier = "fa fa-2x fa-wrench"

[[menu.social]]
    name = "RSS"
    url = "/index.xml"
    weight = 90
    identifier = "fa fa-2x fa-rss"
