site_name: VCMI
site_url: https://vcmi.eu
plugins:
  - include_dir_to_nav
  - blog:
      authors: false
  - patch-retry
  - privacy:
      concurrency: 1
  - search
  - glightbox
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
#  - optimize
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.path
    - navigation.top
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.path
    - content.code.copy
    - content.code.select
  logo: assets/logo.svg
  favicon: assets/favicon.png
  palette:
    scheme: slate
    primary: red
    accent: red
  custom_dir: overrides
nav:
  - Home: index.md
  - Blog: blog/index.md
  - Download: download.md
  - Changelog: ChangeLog.md
  - Mod Repository: Mod Repository
  - FAQ: faq.md
  - About: about.md
  - Players: players
  - Modders: modders
  - Translators: translators
  - Developers: developers
extra:
  social:
    - icon: fontawesome/solid/comments
      link: https://forum.vcmi.eu/
      name: Forum
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/chBT42V
      name: Discord
    - icon: fontawesome/brands/github 
      link: https://github.com/vcmi/vcmi
      name: GitHub
    - icon: fontawesome/brands/facebook 
      link: https://facebook.com/VCMIOfficial
      name: Facebook
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com/VCMIOfficial
      name: X
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/c/VCMIOfficial
      name: YouTube
    - icon: fontawesome/brands/vk 
      link: https://vk.com/VCMIOfficial
      name: VK
    - icon: custom/chatgpt 
      link: https://chatgpt.com/g/g-1kNhX0mlO-vcmi-assistant
      name: ChatGPT
  generator: false
extra_css:
  - theme/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - theme/tablesort.js
copyright: >
  Copyright &copy; 2007 - <span id="copyyear"></span><script>document.getElementById('copyyear').innerHTML = new Date().getFullYear();</script> VCMI team
  <p style="font-size:.42rem !important; margin-bottom: -0.25rem !important;; margin-top: 0.15rem !important;">VCMI, this page and the VCMI Team are in no way associated with or supported by Ubisoft Entertainment. Heroes, Might and Magic, Heroes of Might and Magic and their respective logos are registered trademarks of Ubisoft Entertainment in the U.S. and/or other countries. All Rights Reserved. All other trademarks are properties of their respective owners.</p>
  <p style="font-size:.42rem !important; margin-bottom: -0.6rem !important;">Buy Heroes III on <a href="https://www.gog.com/en/game/heroes_of_might_and_magic_3_complete_edition">gog.com</a>, we don't support piracy! Hosting provided by <a href="https://digitalocean.com/">Digital Ocean</a>. Made with <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a></p>
markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
repo_url: https://github.com/vcmi/vcmi
